export { Navbar } from './UI/Navbar/Navbar';
export { Footer } from './UI/Footer/Footer';
export { Panel } from './UI/Panel/Panel';
export { Title } from './UI/Title/Title';
export { SliderItem } from './UI/Slider/SliderItem';
export { SphereSection } from './UI/SphereSection/SphereSection';
export { SphereCard } from './UI/SphereSection/SphereCard/SphereCard';
export { ProfEquipment } from './UI/ProfEquipment/ProfEquipment';
export { Industry } from './UI/Industry/Industry';
